CC=g++
CFLAGS=-std=c++11 
TARGET=all
TARGET_TEST=test

SRC_TEST    = ./tests
BUILD_TEST = ./build_test
BUILD_DIR    = ./build
SRC_DIR    = ./src
INCLUDE_DIR  = ./include
BOOST = ./third_parties/boost_1_66_0
DOCTEST = ./third_parties

all: ${BUILD_DIR}/dice.o ${BUILD_DIR}/player.o ${BUILD_DIR}/mage.o ${BUILD_DIR}/lucky.o ${BUILD_DIR}/ranger.o ${BUILD_DIR}/warrior.o ${BUILD_DIR}/enemy.o ${BUILD_DIR}/slime.o ${BUILD_DIR}/gnome.o ${BUILD_DIR}/pumpkin.o ${BUILD_DIR}/skeleton.o ${BUILD_DIR}/wolf.o ${BUILD_DIR}/boss.o ${BUILD_DIR}/basic_room.o  ${BUILD_DIR}/pitfall_random.o ${BUILD_DIR}/abism_death_room.o ${BUILD_DIR}/dmg_npc.o ${BUILD_DIR}/mimic_death_room.o ${BUILD_DIR}/life_elixir.o ${BUILD_DIR}/life_fairy.o ${BUILD_DIR}/life_potion.o ${BUILD_DIR}/history_room.o ${BUILD_DIR}/left_right.o ${BUILD_DIR}/quiz_room.o ${BUILD_DIR}/tip_room.o ${BUILD_DIR}/xp_room.o ${BUILD_DIR}/battle_room.o ${BUILD_DIR}/room.o ${BUILD_DIR}/event.o ${BUILD_DIR}/event_battle.o ${BUILD_DIR}/event_interaction.o ${BUILD_DIR}/inicializer.o ${BUILD_DIR}/main.o
	${CC} ${CFLAGS} -o game ${BUILD_DIR}/*.o

test: testdice.o testboss.o testenemy.o testgnome.o testpumpkin.o testskeleton.o testslime.o testwolf.o testplayer.o testlucky.o testranger.o testwarrior.o testbattleroom.o testroom.o testevent.o testeventbattle.o testeventinteraction.o testinicializer.o test.o
	${CC} ${CFLAGS} -o game_test *.o
	mv *.o ${BUILD_TEST}

${BUILD_DIR}/dice.o: ${INCLUDE_DIR}/dice/dice.hpp ${SRC_DIR}/dice/dice.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -c ${SRC_DIR}/dice/dice.cpp -o ${BUILD_DIR}/dice.o

${BUILD_DIR}/player.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${SRC_DIR}/player/player.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/player/player.cpp -o ${BUILD_DIR}/player.o

${BUILD_DIR}/mage.o: ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/mage.hpp ${SRC_DIR}/player/mage.cpp
	${CC} ${CFLAGS}  -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/player/mage.cpp -o ${BUILD_DIR}/mage.o

${BUILD_DIR}/lucky.o: ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/lucky.hpp ${SRC_DIR}/player/lucky.cpp
	${CC} ${CFLAGS}  -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/player/lucky.cpp -o ${BUILD_DIR}/lucky.o

${BUILD_DIR}/ranger.o: ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/ranger.hpp ${SRC_DIR}/player/ranger.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/player/ranger.cpp -o ${BUILD_DIR}/ranger.o

${BUILD_DIR}/warrior.o: ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/warrior.hpp ${SRC_DIR}/player/warrior.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/player/warrior.cpp -o ${BUILD_DIR}/warrior.o

${BUILD_DIR}/enemy.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${SRC_DIR}/enemies/enemy.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/enemy.cpp -o ${BUILD_DIR}/enemy.o

${BUILD_DIR}/slime.o: ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${SRC_DIR}/enemies/slime.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/slime.cpp -o ${BUILD_DIR}/slime.o

${BUILD_DIR}/gnome.o: ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/gnome.hpp ${SRC_DIR}/enemies/gnome.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/gnome.cpp -o ${BUILD_DIR}/gnome.o

${BUILD_DIR}/pumpkin.o: ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${SRC_DIR}/enemies/pumpkin.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/pumpkin.cpp -o ${BUILD_DIR}/pumpkin.o

${BUILD_DIR}/skeleton.o: ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${SRC_DIR}/enemies/skeleton.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/skeleton.cpp -o ${BUILD_DIR}/skeleton.o

${BUILD_DIR}/wolf.o: ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${SRC_DIR}/enemies/wolf.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/wolf.cpp -o ${BUILD_DIR}/wolf.o

${BUILD_DIR}/boss.o: ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${SRC_DIR}/enemies/boss.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/enemies/boss.cpp -o ${BUILD_DIR}/boss.o

${BUILD_DIR}/basic_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${SRC_DIR}/basic_room/basic_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/basic_room.cpp -o ${BUILD_DIR}/basic_room.o

${BUILD_DIR}/pitfall_random.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/pitfall_random.hpp ${SRC_DIR}/basic_room/pitfall_random.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/pitfall_random.cpp -o ${BUILD_DIR}/pitfall_random.o

${BUILD_DIR}/abism_death_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/abism_death_room.hpp ${SRC_DIR}/basic_room/abism_death_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/abism_death_room.cpp -o ${BUILD_DIR}/abism_death_room.o

${BUILD_DIR}/dmg_npc.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${SRC_DIR}/basic_room/dmg_npc.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/dmg_npc.cpp -o ${BUILD_DIR}/dmg_npc.o

${BUILD_DIR}/mimic_death_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${SRC_DIR}/basic_room/mimic_death_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/mimic_death_room.cpp -o ${BUILD_DIR}/mimic_death_room.o

${BUILD_DIR}/life_elixir.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${SRC_DIR}/basic_room/life_elixir.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/life_elixir.cpp -o ${BUILD_DIR}/life_elixir.o

${BUILD_DIR}/life_fairy.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp  ${SRC_DIR}/basic_room/life_fairy.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/life_fairy.cpp -o ${BUILD_DIR}/life_fairy.o

${BUILD_DIR}/life_potion.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${SRC_DIR}/basic_room/life_potion.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/life_potion.cpp -o ${BUILD_DIR}/life_potion.o

${BUILD_DIR}/history_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp  ${SRC_DIR}/basic_room/history_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/history_room.cpp -o ${BUILD_DIR}/history_room.o

${BUILD_DIR}/left_right.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${SRC_DIR}/basic_room/left_right.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/left_right.cpp -o ${BUILD_DIR}/left_right.o

${BUILD_DIR}/quiz_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${SRC_DIR}/basic_room/quiz_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/quiz_room.cpp -o ${BUILD_DIR}/quiz_room.o

${BUILD_DIR}/tip_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp  ${INCLUDE_DIR}/basic_room/tip_room.hpp ${SRC_DIR}/basic_room/tip_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/tip_room.cpp -o ${BUILD_DIR}/tip_room.o

${BUILD_DIR}/xp_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp  ${INCLUDE_DIR}/basic_room/xp_room.hpp ${SRC_DIR}/basic_room/xp_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/basic_room/ -c ${SRC_DIR}/basic_room/xp_room.cpp -o ${BUILD_DIR}/xp_room.o

${BUILD_DIR}/battle_room.o: ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp  ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${SRC_DIR}/battle_room/battle_room.cpp
	${CC} ${CFLAGS} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/battle_room/ -c ${SRC_DIR}/battle_room/battle_room.cpp -o ${BUILD_DIR}/battle_room.o

${BUILD_DIR}/room.o: ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${SRC_DIR}/room/room.cpp
	${CC} ${CFLAGS}  -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/room/ -c ${SRC_DIR}/room/room.cpp -o ${BUILD_DIR}/room.o

${BUILD_DIR}/event.o: ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/event/event.hpp ${SRC_DIR}/event/event.cpp
	${CC} ${CFLAGS} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/room/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/room/  -I ${INCLUDE_DIR}/event/ -c ${SRC_DIR}/event/event.cpp -o ${BUILD_DIR}/event.o

${BUILD_DIR}/event_battle.o: ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/event/event_battle.hpp ${SRC_DIR}/event/event_battle.cpp
	${CC} ${CFLAGS} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -c ${SRC_DIR}/event/event_battle.cpp -o ${BUILD_DIR}/event_battle.o

${BUILD_DIR}/event_interaction.o: ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/basic_room/pitfall_random.hpp  ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/event/event_interaction.hpp ${SRC_DIR}/event/event_interaction.cpp
	${CC} ${CFLAGS} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -c ${SRC_DIR}/event/event_interaction.cpp -o ${BUILD_DIR}/event_interaction.o

${BUILD_DIR}/inicializer.o: ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/pitfall_random.hpp ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp ${INCLUDE_DIR}/event/event_battle.hpp  ${INCLUDE_DIR}/event/event_interaction.hpp ${INCLUDE_DIR}/inicializer/inicializer.hpp ${SRC_DIR}/inicializer/inicializer.cpp
	${CC} ${CFLAGS} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -I ${INCLUDE_DIR}/inicializer -c ${SRC_DIR}/inicializer/inicializer.cpp -o ${BUILD_DIR}/inicializer.o

${BUILD_DIR}/main.o: ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/pitfall_random.hpp ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp ${INCLUDE_DIR}/event/event_battle.hpp  ${INCLUDE_DIR}/event/event_interaction.hpp ${SRC_DIR}/main.cpp
	${CC} ${CFLAGS} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -I ${INCLUDE_DIR}/inicializer -c ${SRC_DIR}/main.cpp -o ${BUILD_DIR}/main.o

testdice.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${SRC_TEST}/dice/testdice.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -c ${SRC_DIR}/dice/dice.cpp  ${SRC_TEST}/dice/testdice.cpp 

testenemy.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${SRC_TEST}/enemies/testenemy.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp  ${SRC_TEST}/enemies/testenemy.cpp

testboss.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${SRC_TEST}/enemies/testboss.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_TEST}/enemies/testboss.cpp 

testgnome.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/gnome.hpp ${SRC_TEST}/enemies/testgnome.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_TEST}/enemies/testgnome.cpp 

testpumpkin.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${SRC_TEST}/enemies/testpumpkin.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_TEST}/enemies/testpumpkin.cpp 

testskeleton.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${SRC_TEST}/enemies/testskeleton.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_TEST}/enemies/testskeleton.cpp 

testslime.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${SRC_TEST}/enemies/testslime.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_TEST}/enemies/testslime.cpp 

testwolf.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${SRC_TEST}/enemies/testwolf.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_TEST}/enemies/testwolf.cpp 

testplayer.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${SRC_TEST}/players/testplayer.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_TEST}/players/testplayer.cpp 

testlucky.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/lucky.hpp ${SRC_TEST}/players/testlucky.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_TEST}/players/testlucky.cpp 

testmage.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/mage.hpp ${SRC_TEST}/players/testmage.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp  ${SRC_TEST}/players/testmage.cpp 

testranger.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/ranger.hpp ${SRC_TEST}/players/testranger.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/ranger.cpp  ${SRC_TEST}/players/testranger.cpp 

testwarrior.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/warrior.hpp ${SRC_TEST}/players/testwarrior.cpp 
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/warrior.cpp  ${SRC_TEST}/players/testwarrior.cpp 

testbattleroom.o: ${DOCTEST}/doctest.h ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp  ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${SRC_TEST}/battle_room/testbattleroom.cpp
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/battle_room/ -c ${SRC_TEST}/battle_room/testbattleroom.cpp 

testroom.o: ${DOCTEST}/doctest.h ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/pitfall_random.hpp  ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp  ${INCLUDE_DIR}/room/room.hpp ${SRC_TEST}/room/testroom.cpp
	${CC} ${CFLAGS}  -I ${DOCTEST} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/room/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_DIR}/player/ranger.cpp ${SRC_DIR}/player/warrior.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_DIR}/battle_room/battle_room.cpp ${SRC_DIR}/basic_room/basic_room.cpp ${SRC_DIR}/basic_room/pitfall_random.cpp ${SRC_DIR}/basic_room/abism_death_room.cpp ${SRC_DIR}/basic_room/dmg_npc.cpp ${SRC_DIR}/basic_room/mimic_death_room.cpp ${SRC_DIR}/basic_room/life_elixir.cpp ${SRC_DIR}/basic_room/life_fairy.cpp ${SRC_DIR}/basic_room/life_potion.cpp ${SRC_DIR}/basic_room/history_room.cpp ${SRC_DIR}/basic_room/left_right.cpp ${SRC_DIR}/basic_room/quiz_room.cpp ${SRC_DIR}/basic_room/tip_room.cpp ${SRC_DIR}/basic_room/xp_room.cpp ${SRC_DIR}/room/room.cpp ${SRC_TEST}/room/testroom.cpp 

testevent.o: ${DOCTEST}/doctest.h ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp ${SRC_TEST}/event/testevent.cpp
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/room/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/room/  -I ${INCLUDE_DIR}/event/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_DIR}/player/ranger.cpp ${SRC_DIR}/player/warrior.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_DIR}/battle_room/battle_room.cpp  ${SRC_DIR}/basic_room/basic_room.cpp ${SRC_DIR}/room/room.cpp  ${SRC_DIR}/event/event.cpp ${SRC_TEST}/event/testevent.cpp 

testeventbattle.o: ${DOCTEST}/doctest.h ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/event/event_battle.hpp ${SRC_TEST}/event/testeventbattle.cpp
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_DIR}/player/ranger.cpp ${SRC_DIR}/player/warrior.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_DIR}/battle_room/battle_room.cpp  ${SRC_DIR}/basic_room/basic_room.cpp ${SRC_DIR}/room/room.cpp  ${SRC_DIR}/event/event.cpp ${SRC_DIR}/event/event_battle.cpp ${SRC_TEST}/event/testeventbattle.cpp 

testeventinteraction.o: ${DOCTEST}/doctest.h ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/basic_room/pitfall_random.hpp  ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp ${INCLUDE_DIR}/event/event.hpp  ${INCLUDE_DIR}/event/event_interaction.hpp ${SRC_TEST}/event/testeventinteraction.cpp
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_DIR}/player/ranger.cpp ${SRC_DIR}/player/warrior.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_DIR}/battle_room/battle_room.cpp  ${SRC_DIR}/basic_room/basic_room.cpp ${SRC_DIR}/basic_room/pitfall_random.cpp ${SRC_DIR}/basic_room/abism_death_room.cpp ${SRC_DIR}/basic_room/dmg_npc.cpp ${SRC_DIR}/basic_room/mimic_death_room.cpp ${SRC_DIR}/basic_room/life_elixir.cpp ${SRC_DIR}/basic_room/life_fairy.cpp ${SRC_DIR}/basic_room/life_potion.cpp ${SRC_DIR}/basic_room/history_room.cpp ${SRC_DIR}/basic_room/left_right.cpp ${SRC_DIR}/basic_room/quiz_room.cpp ${SRC_DIR}/basic_room/tip_room.cpp ${SRC_DIR}/basic_room/xp_room.cpp ${SRC_DIR}/room/room.cpp  ${SRC_DIR}/event/event.cpp ${SRC_DIR}/event/event_battle.cpp ${SRC_DIR}/event/event_interaction.cpp ${SRC_TEST}/event/testeventinteraction.cpp

testinicializer.o: ${DOCTEST}/doctest.h ${BOOST}/boost/variant.hpp ${INCLUDE_DIR}/dice/dice.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp  ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/pitfall_random.hpp ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp ${INCLUDE_DIR}/event/event_battle.hpp  ${INCLUDE_DIR}/event/event_interaction.hpp ${INCLUDE_DIR}/inicializer/inicializer.hpp ${SRC_TEST}/inicializer/testinicializer.cpp
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${BOOST} -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/player/ -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/room -I ${INCLUDE_DIR}/event/ -I ${INCLUDE_DIR}/inicializer -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_DIR}/player/ranger.cpp ${SRC_DIR}/player/warrior.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_DIR}/battle_room/battle_room.cpp ${SRC_DIR}/basic_room/basic_room.cpp ${SRC_DIR}/basic_room/pitfall_random.cpp ${SRC_DIR}/basic_room/abism_death_room.cpp ${SRC_DIR}/basic_room/dmg_npc.cpp ${SRC_DIR}/basic_room/mimic_death_room.cpp ${SRC_DIR}/basic_room/life_elixir.cpp ${SRC_DIR}/basic_room/life_fairy.cpp ${SRC_DIR}/basic_room/life_potion.cpp ${SRC_DIR}/basic_room/history_room.cpp ${SRC_DIR}/basic_room/left_right.cpp ${SRC_DIR}/basic_room/quiz_room.cpp ${SRC_DIR}/basic_room/tip_room.cpp ${SRC_DIR}/basic_room/xp_room.cpp ${SRC_DIR}/room/room.cpp  ${SRC_DIR}/event/event.cpp ${SRC_DIR}/event/event_battle.cpp ${SRC_DIR}/event/event_interaction.cpp  ${SRC_DIR}/inicializer/inicializer.cpp ${SRC_TEST}/inicializer/testinicializer.cpp

test.o: ${DOCTEST}/doctest.h ${BOOST}/boost/variant.hpp  ${INCLUDE_DIR}/enum_type/enum_type.hpp ${INCLUDE_DIR}/enum_winner/enum_winner.hpp ${INCLUDE_DIR}/enemies/slime.hpp ${INCLUDE_DIR}/enemies/pumpkin.hpp ${INCLUDE_DIR}/enemies/skeleton.hpp ${INCLUDE_DIR}/enemies/wolf.hpp ${INCLUDE_DIR}/enemies/boss.hpp ${INCLUDE_DIR}/enemies/enemy.hpp ${INCLUDE_DIR}/player/player.hpp ${INCLUDE_DIR}/player/mage.hpp ${INCLUDE_DIR}/player/lucky.hpp ${INCLUDE_DIR}/player/ranger.hpp ${INCLUDE_DIR}/player/warrior.hpp ${INCLUDE_DIR}/battle_room/battle_room.hpp ${INCLUDE_DIR}/basic_room/basic_room.hpp ${INCLUDE_DIR}/basic_room/pitfall_random.hpp ${INCLUDE_DIR}/basic_room/abism_death_room.hpp  ${INCLUDE_DIR}/basic_room/dmg_npc.hpp ${INCLUDE_DIR}/basic_room/mimic_death_room.hpp ${INCLUDE_DIR}/basic_room/life_elixir.hpp ${INCLUDE_DIR}/basic_room/life_fairy.hpp ${INCLUDE_DIR}/basic_room/life_potion.hpp ${INCLUDE_DIR}/basic_room/history_room.hpp ${INCLUDE_DIR}/basic_room/left_right.hpp ${INCLUDE_DIR}/basic_room/quiz_room.hpp ${INCLUDE_DIR}/basic_room/tip_room.hpp ${INCLUDE_DIR}/basic_room/xp_room.hpp ${INCLUDE_DIR}/room/room.hpp ${INCLUDE_DIR}/event/event.hpp ${INCLUDE_DIR}/event/event_battle.hpp  ${INCLUDE_DIR}/event/event_interaction.hpp ${INCLUDE_DIR}/inicializer/inicializer.hpp ${SRC_TEST}/test.cpp
	${CC} ${CFLAGS} -I ${DOCTEST} -I ${BOOST} -I ${INCLUDE_DIR}/enum_winner/ -I ${INCLUDE_DIR}/enum_type/ -I ${INCLUDE_DIR}/dice/ -I ${INCLUDE_DIR}/enemies/ -I ${INCLUDE_DIR}/player/  -I ${INCLUDE_DIR}/battle_room/ -I ${INCLUDE_DIR}/basic_room/ -I ${INCLUDE_DIR}/room/  -I ${INCLUDE_DIR}/event -I ${INCLUDE_DIR}/inicializer/ -c ${SRC_DIR}/dice/dice.cpp ${SRC_DIR}/enemies/enemy.cpp ${SRC_DIR}/enemies/boss.cpp ${SRC_DIR}/enemies/gnome.cpp ${SRC_DIR}/enemies/pumpkin.cpp ${SRC_DIR}/enemies/skeleton.cpp ${SRC_DIR}/enemies/slime.cpp ${SRC_DIR}/enemies/wolf.cpp ${SRC_DIR}/player/player.cpp ${SRC_DIR}/player/mage.cpp ${SRC_DIR}/player/lucky.cpp ${SRC_DIR}/player/ranger.cpp ${SRC_DIR}/player/warrior.cpp ${SRC_DIR}/battle_room/battle_room.cpp ${SRC_DIR}/basic_room/basic_room.cpp ${SRC_DIR}/basic_room/pitfall_random.cpp ${SRC_DIR}/basic_room/abism_death_room.cpp ${SRC_DIR}/basic_room/dmg_npc.cpp ${SRC_DIR}/basic_room/mimic_death_room.cpp ${SRC_DIR}/basic_room/life_elixir.cpp ${SRC_DIR}/basic_room/life_fairy.cpp ${SRC_DIR}/basic_room/life_potion.cpp ${SRC_DIR}/basic_room/history_room.cpp ${SRC_DIR}/basic_room/left_right.cpp ${SRC_DIR}/basic_room/quiz_room.cpp ${SRC_DIR}/basic_room/tip_room.cpp ${SRC_DIR}/basic_room/xp_room.cpp ${SRC_DIR}/room/room.cpp  ${SRC_DIR}/event/event.cpp ${SRC_DIR}/event/event_battle.cpp ${SRC_DIR}/event/event_interaction.cpp  ${SRC_DIR}/inicializer/inicializer.cpp ${SRC_TEST}/test.cpp

# Rule for cleaning files generated during compilation. 
# Call 'make clean' to use it
clean:
	rm -f ${BUILD_DIR}/* 	
	rm -f ${BUILD_TEST}/* 